# Generated by Django 4.2 on 2023-04-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_doctor_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='doctor', max_length=7),
            preserve_default=False,
        ),
    ]
